name: Scrape editais (Estratégia MED)

on:
  schedule:
    # 07:30 BRT ≈ 10:30 UTC
    - cron: "30 10 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - "scraper.py"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scraper.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: update data/editais.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
